name: Trigger Automation

# Trigger on manually dispatching the workflow
on:
  workflow_dispatch:
    inputs:
      input-string:
        description: 'Enter Url'
        required: true
        default: 'http://203.193.144.20:8005/dashboard'

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: docker.io/selenium/standalone-chrome:latest
        options: >-
          --shm-size 2g
          --name xvfb
          --label testing

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 (using Temurin distribution)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Install Maven
      - name: Install Maven
        run: sudo apt-get install -y maven

      # Install Allure
      - name: Install Allure
        run: |
          curl -o allure.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
          sudo tar -zxvf allure.tgz -C /opt/
          sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure

      # Run TestNG tests
      - name: Run TestNG tests
        run: mvn test -Durl=${{ github.event.inputs.input-string }}

      - name: Generate Allure Report
        run: allure generate --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

