name: Trigger Automation

# Trigger on manually dispatching the workflow
on:
  workflow_dispatch:
    inputs:
      input-string:
        description: 'Enter URL'
        required: true
        default: 'http://203.193.144.20:8005/dashboard/'

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: docker.io/selenium/standalone-chrome:latest
        options: >-
          --shm-size 2g
          --name xvfb
          --label testing

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 (using Adoptium distribution)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Install Maven
        run: sudo apt-get install -y maven


      - name: Install Allure
        run: |
          curl -o allure-2.13.8.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
          sudo tar -zxvf allure-2.13.8.tgz -C /opt/
          sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure

      # Cache Maven dependencies to speed up the process
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies (skip tests during this step)
      - name: Install dependencies
        run: mvn install -DskipTests=true

      # Run the automation tests (TestNG)
      - name: Run TestNG tests
        run: |
          mvn test -Durl=${{ github.event.inputs.input-string }} 
