name: Run Automation Tests

# Trigger on push to the repository or pull request
on:
  workflow_dispatch:
    inputs:
      input-string:
        description: 'Enter URL'
        required: true
        default: 'http://203.193.144.20:8005/dashboard/'

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: docker.io/selenium/standalone-chrome:latest
        options: >-
          --shm-size 2g
          --name xvfb
          --label testing

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK (Java Development Kit) for running the tests
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use Java 11
          distribution: 'adoptopenjdk'  # Use the AdoptOpenJDK distribution

      # Cache Maven dependencies to speed up the process
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies (assuming you're using Maven)
      - name: Install dependencies
        run: mvn install -DskipTests=true

      # Run the automation tests (TestNG)
      - name: Run TestNG tests
        run: mvn test
